# Generated by Django 4.1.2 on 2022-11-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_is_active2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_active2",
        ),
    ]
